# Generated by Django 4.2.2 on 2023-07-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToMany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='language',
            new_name='nameClass',
        ),
    ]
