# Generated by Django 4.2.2 on 2023-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManyToMany', '0002_rename_language_student_nameclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nameClass',
        ),
        migrations.AddField(
            model_name='student',
            name='nameClass',
            field=models.ManyToManyField(to='ManyToMany.class'),
        ),
    ]
